### ISSUE TITLE
Get Engrafo running on Cloud Run

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/engrafo#1022]
At some point we want to migrate arXiv Vanity to use Cloud Run, [triggered with Cloud Tasks](https://cloud.google.com/run/docs/triggering/using-tasks) so it is asynchronous.

- [x] Server #1021 
- [ ] Document how to get it running on Cloud Run & Cloud Tasks
- [ ] Push image to Google Container Registry. The image is currently on Docker Hub (which is S3). This will probably be faster, and mean we don't get charged data transfer.
- [ ] Add webhook to server to report success. Cloud Tasks doesn't seem to have any method of reporting when a task has finished. This will allow arXiv Vanity to be notified of success without having to poll the S3 bucket or whatever.
