### ISSUE TITLE
Instead of rewriting HTML to fit Distill, write CSS for LaTeXML's output

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/engrafo#255]
Currently we rewrite HTML to fit Distill's template. This is a mess, just so we can reuse a few small bits from Distill's template.

I think we should ditch Distill's template and instead write our own CSS to style LaTeXML output.

This means we are blessing LaTeXML as "standard" HTML output for LaTeX, and Engrafo's style becomes reusable and much more useful. We'll also be forced to improve LaTeXML where necessary instead of hacking it with our postprocessing.

We'll still need a post-processing, but this will make Engrafo vastly simpler and easier to maintain.

## Rough plan

- [x] Visual integration tests https://github.com/arxiv-vanity/engrafo/pull/290
- [x] Write a comprehensive set of integration tests to cover current functionality
- [ ] Rewrite CSS for LaTeXML output, ensuring output remains roughly the same using integration test screenshots #324

**Comment by davidar** [comment]
[TeXify](https://texify.davidar.io/) was designed to work with the HTML output by LaTeXML. As @dginev mentioned in #159, it's currently being used by the CorTeX previews, if you wanted to see how it looks on LaTeXML converted articles.

I had a quick look through the open issues, and several of them seem to have already been addressed by TeXify:
- #237
- #228
- #222
- #193
- #101

I'd be happy to help with any issues moving from the Distill template to TeXify, if you're interested?

**Comment by bfirsh** [comment]
Nice thanks! We definitely intend to keep something resembling Distill’s typesetting, but I’ll take a look to see if there’s anything we can reuse. 

One design choice we made was to do pretty much everything server-side for performance. The fact that TeX.js is all client-side may be a blocker to us reusing stuff, but perhaps CSS can be reused.

Generally, is there some way we can collaborate perhaps? I’m not sure how, but if we can avoid duplicating effort that’d benefit us all!

**Comment by dginev** [comment]
My best stab at what is reusable and shareable for now is explicitly and clearly documenting all details of the HTML5 dialect, which I am tracking in https://github.com/brucemiller/LaTeXML/issues/896 and would also help the engrafo effort style things faster.

CSS should be easy to reuse across Distill installations, but is typically vendor-specific, so not immediately obvious how much of it can be reused across websites. A technique I have used before is to contribute back generic upgrades to the main latexml CSS (maintained in the latexml repo), while keeping the more specific rules in the specific project repositories such as engrafo and TeXify, cascading over the generic rules. Will watch this issue, exciting!

**Comment by davidar** [comment]
It's about 35% JS and 65% CSS. A decent amount of the JS is either optional (especially when dealing with LaTeXML output rather than hand-written HTML) or could potentially be performed server-side.

I can understand that you may not want to adopt wholesale some of the more opinionated aspects of TeXify's style (personally I'm quite fond of the [rubrication](https://en.wikipedia.org/wiki/Rubric) aesthetic 😉) so am happy to discuss which parts may be more generally useful (and could perhaps be separated out from the rest).

I guess it depends how closely you're intending sticking to Distill's style (ie. just the general look of it, or more specific details)?

**Comment by bfirsh** [comment]
If you're subscribed to this thread, work has resumed again on this: https://github.com/arxiv-vanity/engrafo/pull/324

**Comment by dginev** [comment]
Kudos for this disciplined redesign! I wanted to write in to let you know that me and @brucemiller are interested in assisting with any blockers you encounter with the HTML dialect of latexml, where you find yourself in need of writing XSLT changes. 

To quote Bruce, the design intention of the HTML dialect has always been to be high level enough that you could realize any styling project via CSS and JS. If it turns out that the HTML markup itself is wrongly structured, incomplete, etc, we are very interested in improving the core LaTeXML XSLTs to a state where you have everything you need in the default dialect. I'll subscribe to the PR and see if bits fly by that we have ideas on.

**Comment by bfirsh** [comment]
@dginev Yes! I am very interested in this too. For the first iteration, I am going to continue rewriting bits of the HTML just because it's quick and dirty and means we can get the job done.

Once, the rewrite is done, we can then incorporate those bits of rewriting into LaTeXML one-by-one. There are a few approaches to this, I think:

- There is some stuff that just needs fixing, which I'll submit PRs for. E.g. semantically, abstracts should be `<h2>` not `<h6>`. It is also annoying that the render time in the footer. It means output is non-deterministic, so you can't write integration tests. 😆
- For some stuff we can add configuration options - e.g. an option for adding custom `<meta>` tags.
- For everything else I can write plugins. For example, we do Mathjax rendering server-side because it makes page loading so much faster. Also, we add links to things which look like links but aren't `\url`s.

There is also another problem: There are some styling things that _need_ to be represented in HTML. For example, I want all figure captions to be below the figure. It's purely a styling thing, but there is no way in CSS of moving figure captions from the top of a figure to the bottom.

It shouldn't work like this for all LaTeXML renders, so it shouldn't be the default. It probably shouldn't be a configuration option either - it is weirdly specific to Engrafo to be configurable. Perhaps this is the sort of thing where it makes sense for us to write a bit of custom XLST.

**Comment by dginev** [comment]
Sounds excellent! For the render time in the footer, we currently have an option if you're interested in stopping it at the latexml end. Just add `--timestamp=0`. I think we've argued in the past whether the default should be for the timestamp to be off or on...

**Comment by bfirsh** [comment]
Oh brilliant! I didn't know that option existed. I should read the documentation more carefully. :)
